kind: pipeline
type: docker

steps:
  - name: test
    image: python:3.13.3-slim-bookworm
    commands:
      - pwd
      - apt-get update
      - DEBCONF_NOWARNINGS=yes apt-get --no-install-recommends --option=Dpkg::Use-Pty=0 install make
      - pip --version
      - pip --disable-pip-version-check install --requirement=requirements.txt --root-user-action=ignore
      - useradd --create-home user
      - '[ "$CI_REPO_REMOTE" ] && chown --recursive user: .'
      - su user -c 'yapf --version'
      - su user -c 'yapf --diff view.py module/blue.py module/red.py module/white.py'
      - su user -c 'pylint --version'
      - su user -c 'pylint --verbose view.py module/blue.py module/red.py module/white.py'
      - su user -c 'mypy --version'
      - su user -c 'mypy view.py module/blue.py module/red.py module/white.py'
      - su user -c 'make clean'
