[browser]

gatherUsageStats = false
serverAddress = "127.0.0.1"

[logger]

level = "error"

[runner]

fastReruns = true
magicEnabled = false

[server]

headless = true
runOnSave = true

[theme]

backgroundColor = "#282a36"
base = "dark"
primaryColor = "#e37792"
secondaryBackgroundColor = "#44475a"
textColor = "#f8f8f8"
